In [21]:
import pandas as pd
import numpy as np

In [40]:
effortdf = pd.DataFrame.from_csv('effort.csv')
weatherdf = pd.DataFrame.from_csv('weather.csv')
droughtdf = pd.DataFrame.from_csv('drought_fig-1.csv')
heavyPrecipdf = pd.DataFrame.from_csv('heavy-precip_fig-1.csv')
precipdf = pd.DataFrame.from_csv('precipitation_fig-1.csv')
temperaturedf = pd.DataFrame.from_csv('temperature_fig-1.csv')
bald_eagledf = pd.DataFrame.from_csv('bald_eagle_counts.csv')
chickadeedf = pd.DataFrame.from_csv('chickadee_counts.csv')

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default arguments are different, so please refer to the documentation for from_csv when changing your function calls
  """Entry point for launching an IPython kernel.
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: FutureWarning: from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default arguments are different, so please refer to the documentation for from_csv when changing your function calls

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: FutureWarning: from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default arguments are different, so please refer to the documentation for from_csv when changing your function calls
  This is separate from the ipykernel package so we can avoid doing imports until
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: FutureWarning: from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default arguments are different, so please refer to the documentation for from_csv when changing your function calls
  after removing the cwd from sys.path.
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: FutureWarning: from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default arguments are different, so please refer to the documentation for from_csv when changing your function calls
  """
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: FutureWarning: from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default arguments are different, so please refer to the documentation for from_csv when changing your function calls

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:7: FutureWarning: from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default arguments are different, so please refer to the documentation for from_csv when changing your function calls
  import sys
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:8: FutureWarning: from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default arguments are different, so please refer to the documentation for from_csv when changing your function calls

In [41]:
temperaturedf

,Earth's surface,Lower troposphere (measured by satellite) (UAH),Lower troposphere (measured by satellite) (RSS)
Year,,,
1901-01-01,-0.15,NaN,NaN
1902-01-01,-0.43,NaN,NaN
1903-01-01,-1.40,NaN,NaN
1904-01-01,-0.86,NaN,NaN
1905-01-01,-1.02,NaN,NaN
1906-01-01,-0.29,NaN,NaN
1907-01-01,-0.54,NaN,NaN
1908-01-01,0.06,NaN,NaN
1909-01-01,-0.59,NaN,NaN
1910-01-01,0.40,NaN,NaN
1911-01-01,0.01,NaN,NaN
1912-01-01,-1.79,NaN,NaN
1913-01-01,-0.48,NaN,NaN
1914-01-01,-0.18,NaN,NaN
1915-01-01,-0.57,NaN,NaN
1916-01-01,-1.17,NaN,NaN
1917-01-01,-1.96,NaN,NaN
1918-01-01,-0.15,NaN,NaN
1919-01-01,-0.47,NaN,NaN
1920-01-01,-0.95,NaN,NaN
1921-01-01,1.78,NaN,NaN
1922-01-01,0.01,NaN,NaN
1923-01-01,-0.38,NaN,NaN
1924-01-01,-1.43,NaN,NaN
1925-01-01,0.50,NaN,NaN
1926-01-01,-0.07,NaN,NaN
1927-01-01,0.13,NaN,NaN
1928-01-01,-0.10,NaN,NaN
1929-01-01,-1.17,NaN,NaN
1930-01-01,-0.04,NaN,NaN
...,...,...,...
1986-01-01,1.30,0.975135,1.072173
1987-01-01,1.31,1.015635,1.259373
1988-01-01,0.61,0.568635,0.711273
1989-01-01,-0.18,0.624135,0.391023
1990-01-01,1.49,1.492635,1.399923
1991-01-01,1.14,1.158135,1.107423
1992-01-01,0.58,0.529635,0.554373
1993-01-01,-0.76,-0.367365,-0.427527
1994-01-01,0.85,0.882135,1.100223
1995-01-01,0.63,0.649635,0.837573
1996-01-01,-0.13,0.400635,0.319173
1997-01-01,0.18,0.307635,0.417573
1998-01-01,2.21,1.662135,1.868673
1999-01-01,1.86,1.882635,1.869423
2000-01-01,1.25,1.366635,1.395573
2001-01-01,1.68,1.219635,1.414323
2002-01-01,1.19,0.864135,0.941373
2003-01-01,1.24,1.132635,1.323273
2004-01-01,1.08,0.702135,0.829023
2005-01-01,1.62,1.338135,1.394073
2006-01-01,2.23,1.791135,1.528623
2007-01-01,1.63,1.696635,1.638273
2008-01-01,0.27,0.547635,0.259773
2009-01-01,0.37,0.736635,0.415173
2010-01-01,0.96,1.090635,0.828573
2011-01-01,1.16,1.213635,0.946473
2012-01-01,3.26,2.506635,2.375523
2013-01-01,0.41,0.715635,0.334473
2014-01-01,0.52,0.714135,0.333123
2015-01-01,2.38,2.173635,2.057073